---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: sample-app
  labels:
    app: sample-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sample-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-app
  namespace: sample-app
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: sample-app
  namespace: sample-app
  annotations:
    kubernetes.io/service-account.name: "sample-app"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: sample-app
      app: sample-app
  template:
    metadata:
      labels:
        service: sample-app
        app: sample-app
      # annotations:
      #   vault.hashicorp.com/agent-inject: "true"
      #   vault.hashicorp.com/role: "sample-app"

      #   vault.hashicorp.com/agent-inject-secret-app.env: ""
      #   vault.hashicorp.com/agent-inject-template-app.env: ""
      #   vault.hashicorp.com/agent-inject-command-app.env: ""

    spec:
      serviceAccountName: sample-app
      containers:
        - name: sample-app
          image: joatmon08/sample-vault-app:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: DB_ADDRESS
              value: getting-into-vault.cl3xt9calu0m.us-east-1.rds.amazonaws.com
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: password
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 30